repository_names:
  - datamapper/dm-session
  - datamapper/dm-mapper
  - datamapper/dm-relation-graph
  - datamapper/devtools
  - dkubb/adamantium
  - dkubb/ice_nine
  - dkubb/equalizer
  - dkubb/descendants_tracker
  - dkubb/abstract_type
  - dkubb/veritas
  - dkubb/veritas-sql-generator
  - dkubb/veritas-optimizer
  - dkubb/veritas-do-adapter
  - solnic/coercible
  - solnic/virtus
  - mbj/veritas-mongo-adapter
  - mbj/veritas-elasticsearch-adapter
  - mbj/veritas-arango-adapter
  - mbj/veritas-fuzzer
  - mbj/veritas-sexp
  - mbj/aql
  - mbj/anima
  - mbj/mutant
  - mbj/to_source
  - mbj/aequitas
  - mbj/inflecto
team:
  - name: Dan Kubb
    nick: dkubb
  - name: Piotr Solnica
    nick: solnic
  - name: Martin Gamsjaeger
    nick: solnic
  - name: Markus Schirp
    nick: mbj
