projects:
  - datamapper/dm-session
  - datamapper/dm-mapper
  - datamapper/dm-relation-graph
  - datamapper/devtools
  - dkubb/adamantium
  - dkubb/ice_nine
  - dkubb/equalizer
  - dkubb/descendants_tracker
  - dkubb/abstract_type
  - dkubb/veritas
  - dkubb/veritas-sql-generator
  - dkubb/veritas-optimizer
  - dkubb/veritas-do-adapter
  - dkubb/yardstick
  - solnic/coercible
  - solnic/virtus
  - mbj/veritas-mongo-adapter
  - mbj/veritas-elasticsearch-adapter
  - mbj/veritas-arango-adapter
  - mbj/veritas-fuzzer
  - mbj/veritas-sexp
  - mbj/aql
  - mbj/anima
  - mbj/mutant
  - mbj/to_source
  - mbj/aequitas
  - mbj/inflecto
team:
  - name: Dan Kubb
    nick: dkubb
    twitter: dkubb
    github: dkubb
  - name: Piotr Solnica
    nick: solnic
    twitter: dkubb
  - name: Martin Gamsjaeger
    nick: solnic
    twitter: _solnic_
  - name: Markus Schirp
    nick: mbj
    twitter: _m_b_j_
sponsors:
  - name: Triagens
    url: https://triagens.com
    markdown: |
      Triagens sponsored the development of the [veritas-arango-adapter](https://github.com/mbj/veritas-arango-adapter).
      This allowed @mbj to spend more time on the project.
  - name: Schirp DSO
    url: https://schirp-dso.com
    markdown: |
      The company lead/owned by @mbj allowed him to spend time on the project. Sometimes to much.
