page: 
  title: DataMapper2 - Yeah it's beautiful code!
  meta_description: 
  heading:
projects:
  - 
    name: datamapper/dm-session
  - 
    name: datamapper/dm-mapper
  # Undecided future
  #- 
  #  name: datamapper/dm-relation-graph
  - 
    name: datamapper/devtools
  - 
    name: dkubb/adamantium
  - 
    name: dkubb/ice_nine
  - 
    name: dkubb/equalizer
  - 
    name: dkubb/descendants_tracker
  - 
    name: dkubb/abstract_type
  - 
    name: dkubb/axiom
  - 
    name: dkubb/axiom-sql-generator
  - 
    name: dkubb/axiom-optimizer
  - 
    name: dkubb/axiom-do-adapter
  - 
    name: dkubb/yardstick
  - 
    name: dkubb/axiom-types
  - 
    name: dkubb/yardstick
  - 
    name: solnic/coercible
  - 
    name: solnic/virtus
  - 
    name: mbj/dm-status
  - 
    name: mbj/axiom-mongo-adapter
  - 
    name: mbj/axiom-elasticsearch-adapter
  - 
    name: mbj/axiom-arango-adapter
  - 
    name: mbj/axiom-fuzzer
  - 
    name: mbj/axiom-sexp
  - 
    name: mbj/aql
  - 
    name: mbj/concord
  - 
    name: mbj/esearch
  - 
    name: mbj/anima
  - 
    name: mbj/mutant
  - 
    name: mbj/unparser
  - 
    name: mbj/to_source
  - 
    name: mbj/aequitas
  - 
    name: mbj/inflecto
  - 
    name: mbj/ducktrap
team:
  - name: Dan Kubb
    nick: dkubb
    twitter: dkubb
    github: dkubb
  - name: Piotr Solnica
    nick: solnic
    twitter: dkubb
  - name: Martin Gamsjaeger
    nick: solnic
    twitter: _solnic_
  - name: Markus Schirp
    nick: mbj
    twitter: _m_b_j_
sponsors:
  - name: Triagens
    url: https://triagens.com
    markdown: |
      Triagens sponsored the development of the [axiom-arango-adapter](https://github.com/mbj/axiom-arango-adapter).
      This allowed @mbj to spend more time on the project.
  - name: Schirp DSO
    url: https://schirp-dso.com
    markdown: |
      The company lead/owned by @mbj allowed him to spend (sometimes too much) time on the project. 
