page: 
  title: DataMapper2 - Yeah it's beautiful code!
  meta_description: 
projects:
  - datamapper/dm-session
  - datamapper/dm-mapper
  # Undecided future
  # - datamapper/dm-relation-graph
  - datamapper/devtools
  - dkubb/adamantium
  - dkubb/ice_nine
  - dkubb/equalizer
  - dkubb/descendants_tracker
  - dkubb/abstract_type
  - dkubb/axiom
  - dkubb/axiom-sql-generator
  - dkubb/axiom-optimizer
  - dkubb/axiom-do-adapter
  - dkubb/yardstick
  - dkubb/axiom-types
  - dkubb/yardstick
  - solnic/coercible
  - solnic/virtus
  - mbj/dm-status
  - mbj/axiom-mongo-adapter
  - mbj/axiom-elasticsearch-adapter
  - mbj/axiom-arango-adapter
  - mbj/axiom-fuzzer
  - mbj/axiom-sexp
  - mbj/aql
  - mbj/concord
  - mbj/elasticsearch
  - mbj/anima
  - mbj/mutant
  - mbj/unparser
  - mbj/to_source
  - mbj/aequitas
  - mbj/inflecto
  - mbj/ducktrap
team:
  - name: Dan Kubb
    nick: dkubb
    twitter: dkubb
    github: dkubb
  - name: Piotr Solnica
    nick: solnic
    twitter: dkubb
  - name: Martin Gamsjaeger
    nick: solnic
    twitter: _solnic_
  - name: Markus Schirp
    nick: mbj
    twitter: _m_b_j_
sponsors:
  - name: Triagens
    url: https://triagens.com
    markdown: |
      Triagens sponsored the development of the [axiom-arango-adapter](https://github.com/mbj/axiom-arango-adapter).
      This allowed @mbj to spend more time on the project.
  - name: Schirp DSO
    url: https://schirp-dso.com
    markdown: |
      The company lead/owned by @mbj allowed him to spend (sometimes too much) time on the project. 
