---
UncommunicativeParameterName:
  accept: []
  exclude: []
  enabled: false # Todo enable
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
TooManyMethods:
  max_methods: 13 # Todo decrease to 10
  exclude: []
  enabled: true
  max_instance_variables: 3
UncommunicativeMethodName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList:
  max_params: 2 
  exclude: []
  enabled: true
  overrides: {}
FeatureEnvy:
  exclude:
  - Status::Action#page_response
  - Status::Application#members
  - Status::Application#projects
  - Status::Application#sponsors
  - Status::Builder::Updater#asset_env_index
  enabled: true
ClassVariable:
  exclude: []
  enabled: true
BooleanParameter:
  exclude: []
  enabled: true
IrresponsibleModule:
  exclude: []
  enabled: false # Fix false positives and reenable
UncommunicativeModuleName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators:
  ignore_iterators: []
  exclude: []
  enabled: true
  max_allowed_nesting: 1
TooManyStatements:
  max_statements: 8 
  exclude: []
  enabled: true
DuplicateMethodCall:
  allow_calls: []
  exclude: []
  enabled: true
  max_calls: 1 
UtilityFunction:
  max_helper_calls: 0 
  exclude: 
  - Status::Action#page_response
  - Status::Builder#asset_env_index
  - Status::Builder::Updater#asset_env_index
  enabled: true
Attribute:
  exclude: []
  enabled: false
UncommunicativeVariableName:
  accept: [] # TODO remove them
  exclude: []
  enabled: false
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
RepeatedConditional:
  exclude: []
  enabled: true
  max_ifs: 1 
DataClump:
  exclude: []
  enabled: true
  max_copies: 2 
  min_clump_size: 2 
ControlParameter:
  exclude: []
  enabled: true
LongYieldList:
  max_params: 1
  exclude: []
  enabled: true
