page:
  title:            The spec project
  heading:          It is specified stuff
  meta_description: The status page for the spec project
projects:
  - foo/bar
team:
  - name: John Doe
    nick: johnd
    twitter: johnd
    github: jojnd
sponsors:
  - name: Snake Oil Inc
    url: https://example.com
    markdown: |
      The silver bullet!
